#!/bin/sh
# vim: set ft=sh sw=2 et :

install_brew() {
  # install Homebrew if it's missing
  if ! command -v brew > /dev/null 2>&1; then
    echo "brew 命令不存在，请使用linuxbrew用户安装homebrew"
  fi
}

configure_zsh() {
  # FIXME: We deserve better
  source $HOME/.zshrc
}

configure_vim() {
  # Install vim-plug for Vim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +'PlugInstall --sync' +qa
  # Install vim-plug for Neovim
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  nvim +'PlugInstall --sync' +qa
}

system_type=$(uname -s)

echo $system_type

install_brew

# configure_zsh
# configure_vim
